export enum KFK_NAMES {
  BANK_SERVICE = 'BANK_SERVICE',
  SAVINGS_SERVICE = 'SAVINGS_SERVICE',
  BILLS_SERVICE = 'BILLS_SERVICE',
  INSURANCE_SERVICE = 'INSURANCE_SERVICE',
  STOCK_TRADING_SERVICE = 'STOCK_TRADING_SERVICE',
  LOAN_SERVICE = 'LOAN_SERVICE',
  INVESTMENT_SERVICE = 'INVESTMENT_SERVICE',
  CREDIT_CARD_SERVICE = 'CREDIT_CARD_SERVICE',
}

export enum KFK_CLIENTS {
  BANK_CLIENT = 'BANK_CLIENT',
  SAVINGS_CLIENT = 'SAVINGS_CLIENT',
  BILLS_CLIENT = 'BILLS_CLIENT',
  INSURANCE_CLIENT = 'INSURANCE_CLIENT',
  STOCK_TRADING_CLIENT = 'STOCK_TRADING_CLIENT',
  LOAN_CLIENT = 'LOAN_CLIENT',
  INVESTMENT_CLIENT = 'INSURANCE_CLIENT',
  CREDIT_CARD_CLIENT = 'CREDIT_CARD_CLIENT',
}

export enum KFK_GROUPS {
  BANK_GROUP = 'BANK_GROUP',
  SAVINGS_GROUP = 'SAVINGS_GROUP',
  BILLS_GROUP = 'BILLS_GROUP',
  INSURANCE_GROUP = 'INSURANCE_GROUP',
  STOCK_TRADING_GROUP = 'STOCK_TRADING_GROUP',
  LOAN_GROUP = 'LOAN_GROUP',
  INVESTMENT_GROUP = 'INVESTMENT_GROUP',
  CREDIT_CARD_GROUP = 'CREDIT_CARD_GROUP',
}

export enum ERROR_CODES {
  ILLEGAL_TRANSACTION_STATUS = 102,
  ILLEGAL_STATUS_TRANSITION = 103,
  WALLET_LOCKED = 104,
  INSUFFICIENT_WALLET_BALANCE = 105,
}

export const errorMessages = {
  102: 'Transaction Update Failed: Unknown Transaction',
  103: 'Illegal Status Transition',
  104: 'There is an pending transaction on your wallet.',
};

export const FEE = {
  bill: 0,
  convert: 0,
  creditCard: 0,
  investment: 0,
  internalTransfer: 0,
  loan: 0,
  stock: 0,
  insurance: 0,
  withdrawal: 0,
  deposit: 0,
  savings: 0,
};
